### ISSUE TITLE
Create a release using the semantic versioning

### ISSUE THREAD

**Issue by JeffBNimble** [hubertr/Swell#13]
I'm trying to reference your project using Carthage and it won't resolve since you have no releases. Would you mind creating a release, even if it's something like 0.0.1?

Carthage apparently will not resolve anything that doesn't have a release. See [https://github.com/Carthage/Carthage](here) for more info.

**Comment by jspahrsummers** [comment]
Versioned releases help with dependency resolution, but Carthage doesn't _require_ them. You can use a [ref name or SHA](https://github.com/Carthage/Carthage/blob/7a0153cc164e301c46527f6e20c886728a0dc218/Documentation/Artifacts.md#version-requirement) as well.

(Sorry for the drive-by! :stuck_out_tongue_winking_eye:)

**Comment by hubertr** [comment]
I have to admit I haven't looked into creating releases.  I'll spend some time reviewing the specifics for this.  I do like having version numbers where possible so people can at least know easily if there's been an update.

**Comment by hubertr** [comment]
0.5.0 tagged.
