### ISSUE TITLE
Function in Formatter contains Optional()

### ISSUE THREAD

**Issue by broglep-koubachi** [hubertr/Swell#4]
When using the function name in the flex formatter, the resulting string contains "Optional("..")" text.
Based on the code at https://developer.apple.com/swift/blog/?id=15 it looks like that the method signature of https://github.com/hubertr/Swell/blob/master/Swell/Logger.swift#L37 could be changed to use the non optional types. 

Or is there a specific reason why you used the optional?
Another solution would be to fix the flex formatter to first try to unwrap optionals before printing them.

**Comment by yoichitgy** [comment]
I fixed the issue and sent a pull request. The cause of the issue was just lack of unwrapping an optional value. You can use Swell from Objective-C after merging the pull request.

Thank you for the simple structure of Swell to look through.

**Comment by hubertr** [comment]
Hi everyone,

I pushed an update that fixes this issue.  Thanks so much for reporting this.  I do apologize for not being too responsive with the issues.  I see them when they are filed, however severe time constraints prevent me from responding in a timely manner.  

I've also been wondering what steps I can take to fix that problem with respect to Swell.
